FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# KF2

Polls is a simple API allowing consumers to view polls and vote in them.

## Userss Collection [/users]

### List All Users [GET]

+ Request (application/json)
    + Headers
    
            Location: /users
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZHwxMzI0NTYiLCJleHAiOjEzOTI4MTc4ODQsImF1ZCI6InRvcGNvZGVyIiwiaWF0IjoxMzkyNzU3ODg0fQ.7X2IKkiyyI1ExSM5GNpdhJ8fGGK5-oAjzccX6YL_BKY

+ Response 200
    
        [
            {
                "type":"user",
                "publicId": eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9,
                "personalInfo":{
                    "firstName": "Gigi",
                    "lastName": "Migi"
                }
            }
        ]

+ Response 401 (application/json)

        {
            "name":"Unauthorized",
            "value":"401",
            "description":"Authentication credentials were missing or incorrect."
        }

+ Response 403 (application/json)

        {
            "name":"Forbidden",
            "value":"403",
            "description":"The request is understood, but it has been refused or access is not allowed."
        }